### DISCUSSION TITLE
Any way to use HA for notifications when a vent looses connectivity?

### DISCUSSION THREAD

**Discussion by ptr727** [RobertD502/home-assistant-flair#75] [Q&A] [answered]
I rarely look at the Flair mobile app, but I do see there are some alerts about vents that lost connectivity.  
I use HA alerts for most other of importance things, is there a way to get offline notifications from the integration to use in an automation, e.g. connectivity state, or something like that?

**Comment by RobertD502** [comment, marked as answer]
Yes, I programmed the `cover` entity for a vent to become unavailable if the Flair API reports a vent as being offline. In Home Assistant, you can use if a vent `cover` entity has a state of `unavailable` as the trigger for your notification automation.

Note: In addition to the cover entity being unavailable when Flair reports the vent as being offline, Home Assistant, on its own, will set EVERY entity for the Flair integration to unavailable if polling the API fails to return any data (which is bound to happen from time to time when dealing with a cloud-based API). So, I highly recommend you add a condition in your automation that will only fire off the notification if the state of the fan's cover entity has remained `unavailable` for an extended period of time (e.g., 4 min). This way you aren't sending a notification when there is a one-off hiccup in the API / every time the vent goes offline for a few seconds - I myself didn't have a check and got constant notifications until I added the condition. You aren't aware of how frequently a vent may go offline and quickly back online if you are using the Flair app for notifications since they also seem to use a time condition before they consider sending a push notification from the app.

**Reply by ptr727** [reply]
Thx, I'll try it out.

**Reply by RobertD502** [reply]
@ptr727 

If you update to `0.2.1`, you can utilize the `Connection status` binary sensor for a vent to determine if it is offline instead of looking for an `unavailable` state for a vent cover entity.

- When the state of the binary sensor is `on`, the vent is online.
- When the state of the binary sensor is `off`, the vent is offline. 

Using a condition, as discussed above, still applies and is recommended.

**Reply by ptr727** [reply]
Ok, I'll give that a try as well, I did create a notification for `unavailable` as state.  (currently device by device, should try to create a blueprint to do it for any at some point)

**Reply by RobertD502** [reply]
Don't even need a blueprint. You can create a single automation and add each one of the vent Connection status binary sensors as a trigger and the "to" state as "Disconnected" (which looks for a binary sensor state of off). Then set your "for" time to the time you want a vent to be offline before the action of the automation is ran.

For the notification action set the message to {{device_attr("trigger.to_state.entity_id", "name")}}

For example a message of:

'{{device_attr("trigger.to_state.entity_id", "name")}} vent is offline.'

So, whenever any of the vent connection status binary sensors shows a vent as disconnected for the duration of time you set, the message portion of the notification will use the entity id of the binary sensor to fetch the "device" name to use in the message.

For example:
1. Automation uses `binary_sensor.bedroom_left_connection_status`, `binary_sensor.bedroom_right_connection_status` as the trigger and checks for the to state to be Disconnected for 5 min.
2. Bedroom left vent connection status goes to offline for 5 minutes which results in a notification of "Bedroom left vent is offline." Getting sent to you.

By using the binary sensory entity ID to fetch the device name this binary sensor is related to, you can have nice looking messages instead of the message using the friendly name of the binary sensor itself in the message.


If you were to get another Flair vent, it would be as easy as just adding the connection status binary sensor for that new vent to the list of triggers in that single automation.

**Reply by ptr727** [reply]
Reason I considered a blueprint is so I do not need to "add each one" that is cumbersome, I'd like to get notified if "any flair vent" is offline, similar to how e.g. low battery blueprints works, any device, with a battery, that reports low, in this case I'd like any flair vent that is disconnected.

**Reply by RobertD502** [reply]
Ah I see. Sorry, I tend to use node red for my automations, so I didn't grasp what you were trying to achieve.

**Reply by RobertD502** [reply]
@ptr727 

I see that the low battery blueprint automation is executed on a time basis (seems that this is the workaround since the Home Assistant trigger `entity_id` field doesn't accept templating).

So, if you go down this route, you can set a timed automation with the following template variable (named `offline_flair_vents`, for example):

``` jinja
{% set flair_list = integration_entities("flair") | list %}
{% set conn_entities = namespace(entities=[]) %}
{% set vent_conn_list = namespace(entities=[]) %}
{% set offline_vents = namespace(entities=[]) %}
{% for entity in flair_list %}
  {% if is_state_attr(entity, "device_class", "connectivity") %}
    {% set conn_entities.entities = conn_entities.entities + [entity] %}
  {% endif %}
{% endfor %}
{% for entity in conn_entities.entities %}
  {% if is_device_attr(device_id(entity), "model", "Vent") %}
    {% set vent_conn_list.entities = vent_conn_list.entities + [entity] %}
  {% endif %}
{% endfor %}
{% for vent in vent_conn_list.entities %}
  {% if is_state(vent, "off") %}
    {% set offline_vents.entities = offline_vents.entities + [device_attr(vent, "name")] %}
  {% endif %}
{% endfor %}
{{ offline_vents.entities | join(', ') | replace(', ', '\n') }}
```

The template above looks at any Vent device in the Flair integration and adds the name of the Vent to the `offline_flair_vents` variable if the associated connection status binary sensor is `off`.

Then you add a template condition to the notification action that checks to make sure the `offline_flair_vents` variable isn't empty (only send a notification if there is one or more vents offline):

``` jinja
{{ offline_flair_vents != '' }}
```

And construct a message of:

```jinja
'Offline Flair Vents: {{ offline_flair_vents }}`
```

**Reply by ptr727** [reply]
I created a variant that alerts on the condition being met vs. on a timer, but I can use your code to adapt.

Low battery:

```yaml
blueprint:
  name: Battery low alert
  description: Send a notification when a battery low condition triggers
  domain: automation
  input:
    exclude:
      name: Excluded sensors
      description: Sensors to exclude
      default:
        entity_id: []
      selector:
        target:
          entity:
            device_class: battery
    actions:
      name: Actions to take
      description: E.g. Battery low reported by {{ trigger.event.data.new_state.attributes.friendly_name }}
      selector:
        action: null
trigger:
- event_data: {}
  event_type: state_changed
  platform: event
condition:
- condition: template
  value_template: '{{ trigger.event.data.new_state.attributes.device_class == "battery" }}'
- condition: template
  value_template: '{{ trigger.event.data.new_state.state == "on" }}'
action:
- choose: []
  default: !input 'actions'
mode: single
```

Leak detected:

```yaml
blueprint:
  name: Leak sensor alert
  description: Send a notification when a leak sensor triggers
  domain: automation
  input:
    exclude:
      name: Excluded leak sensors
      description: Leak sensors to exclude
      default:
        entity_id: []
      selector:
        target:
          entity:
            device_class: moisture
    actions:
      name: Actions to take
      description: E.g. Leak reported by {{ trigger.event.data.new_state.attributes.friendly_name }}
      selector:
        action: null
trigger:
- event_data: {}
  event_type: state_changed
  platform: event
condition:
- condition: template
  value_template: '{{ trigger.event.data.new_state.attributes.device_class == "moisture" }}'
- condition: template
  value_template: '{{ trigger.event.data.new_state.state == "on" }}'
action:
- choose: []
  default: !input 'actions'
mode: single
```
